name = "notica"
pages_build_output_dir = "dist"

[[build.rules]]
type = "Text"
globs = ["**/*.html"]

[[d1_databases]]
binding = "notica_db"
database_id = "0d2107fc-5a5d-4db8-a211-8c0704268cd4"
database_name = "notica_db"

[[kv_namespaces]]
binding = "NOTICA_KV"
id = "db57b0db052743b9b0c74bc740512ab3"
preview_id = "db57b0db052743b9b0c74bc740512ab3"

[vars]
JWT_SECRET = "IKjCzrpU2mdrRs53nNg2vOrr818JrY6G"
